### PR TITLE
Add initial MileRAT hashing algo

### PR DESCRIPTION
**Pull request by Still34**

### CODE REVIEW

**Comment by Still34** [comment]
Not entirely sure what's causing the failure here - help appreciated

**Comment by herrcore** [comment]
> Not entirely sure what's causing the failure here - help appreciated

This algorithm already exists https://github.com/OALabs/hashdb/blob/fef32157a39a2c4315faa847aef25981576913f8/algorithms/mul83_add.py#L25

You can hunt for hashes using the hunt endpoint https://hashdb.openanalysis.net/#tag/hunt if the hashes used by this algo do not show up please log a bug.

For future reference there is a test that will automatically check for hash algorithm collisions that you can run locally (step 6)

https://github.com/OALabs/hashdb#how-to-add-new-hashes

**Comment by Still34** [comment]
Huh, yeah, the main reason why I created this PR in the first place is that it did not show up on the hunted results. Strange. I'll look into it later.

**Comment by Still34** [comment]
For reference, `GetProcAddress` == `0x1AB9B854` in the actual code.

**Comment by Still34** [comment]
Yeah, I could not get any hits with existing algos.
image

**Pull request closed without merging**
